path:
  model_directory: ./model-${exp.model_type}
  mlflow_dir: ./mlruns
exp:
  fs: 125
  N_fold: 5
  random_state: 100
  model_type: mlpbp
  data_name: bcg
  exp_name: ${exp.data_name}-${exp.model_type}
  exp_detail: lr-${param_model.lr}_wd-${param_model.wd}_bs-${param_model.batch_size}_max_epochs-${param_trainer.max_epochs}_seed-${param_model.seed}
  subject_dict: ../../datasets/splitted/${exp.data_name}_dataset/signal_fold
  loader: waveform
  cv: cv
param_loader:
  ppg_norm: loc_mm
  bp_norm: glob_mm
objective:
  type: val_mse
  mode: min
param_trainer:
  max_epochs: 100
  check_val_every_n_epoch: 1
  progress_bar_refresh_rate: 5
  gpus: '0'
  auto_lr_find: true
  auto_scale_batch_size: binsearch
param_early_stop:
  monitor: ${objective.type}
  min_delta: 0.0
  patience: 10
  verbose: true
  mode: ${objective.mode}
param_model:
  N_epoch: 256
  batch_size: 256
  lr: 0.001
  in_channels: 1
  num_patch: 625
  num_classes: 2
  dim: 128
  depth: 6
  token_dim: 512
  channel_dim: 512 
  dropout: 0.2
  wd: 0
  seed: 0
logger:
  param_ckpt:
    monitor: ${objective.type}
    filename: '{epoch:02d}-{${objective.type}:.3f}'
    save_top_k: 1
    mode: ${objective.mode}

